version: '3'

services:

  comments:
    build:
      context: ../comments
      dockerfile: Dockerfile
    image: bertcatsburg/comments:0.0.1
    container_name: comments
    depends_on:
    - events
    ports:
      - "4001:4001"
    volumes:
      - ../data/comments:/app/data
      - ./container/.profile:/root/.profile
    environment:
      - DATA=/app/data/commentsService.json
    command: ["npm", "run", "startprod"]

  posts:
    build:
      context: ../posts
      dockerfile: Dockerfile
    image: bertcatsburg/posts:0.0.1
    container_name: posts
    depends_on:
    - events
    ports:
      - "4000:4000"
    volumes:
      - ../data/posts:/app/data
      - ./container/.profile:/root/.profile
    environment:
      - DATA=/app/data/postsService.json
    command: ["npm", "run", "startprod"]

  moderation:
    build:
      context: ../moderation
      dockerfile: Dockerfile
    image: bertcatsburg/moderation:0.0.1
    container_name: moderation
    depends_on:
    - events
    ports:
      - "4003:4003"
    volumes:
      - ../data/moderation:/app/data
      - ./container/.profile:/root/.profile
    environment:
      - DATA=/app/data/moderationService.json
    command: ["npm", "run", "startprod"]

  query:
    build:
      context: ../query
      dockerfile: Dockerfile
    image: bertcatsburg/query:0.0.1
    container_name: query
    depends_on:
    - events
    ports:
      - "4002:4002"
    volumes:
      - ../data/query:/app/data
      - ./container/.profile:/root/.profile
    environment:
      - DATA=/app/data/queryService.json
    command: ["npm", "run", "startprod"]

  events:
    build:
      context: ../event-bus
      dockerfile: Dockerfile
    image: bertcatsburg/events:0.0.1
    container_name: events
    ports:
      - "4005:4005"
    volumes:
      - ../data/events:/app/data
      - ./container/.profile:/root/.profile
    environment:
      - DATA=/app/data/eventsService.json
    command: ["npm", "run", "startprod"]

  client:
    build:
      context: ../client
      dockerfile: Dockerfile
    image: bertcatsburg/client:0.0.1
    container_name: client
    depends_on:
      - events
      - posts
      - comments
      - query
      - moderation
    ports:
      - "3000:3000"
    volumes:
      - ./container/.profile:/root/.profile
    command: [ "npm", "start" ]




networks:
  microservices-network:
    external: true
