apiVersion: apps/v1
kind: Deployment
metadata:
  name: posts-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: posts
  template:
    metadata:
      labels:
        app: posts
    spec:
      volumes:
        - name: post-data
          persistentVolumeClaim:
            claimName: data-pv-claim
      containers:
        - name: posts
          image: bertcatsburg/posts:latest
          command: [ "npm", "run", "startprod" ]
          volumeMounts:
            - mountPath: "/app/data"
              name: post-data
          imagePullPolicy: Never
          env:
            - name: DATA
              value: "/app/data/postsService.json"
---
apiVersion: v1
kind: Service
metadata:
  name: posts-clusterip-srv
spec:
  selector:
    app: posts
  type: ClusterIP
  ports:
    - name: posts
      protocol: TCP
      port: 4005
      targetPort: 4005


