apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: data-pv-claim
spec:
  storageClassName: manual
  volumeName: data-pv
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
