apiVersion: apps/v1
kind: Deployment
metadata:
  name: query-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: query
  template:
    metadata:
      labels:
        app: query
    spec:
      containers:
        - name: posts
          image: bertcatsburg/query:latest
          command: [ "npm", "run", "startprod" ]
          imagePullPolicy: Never
          env:
            - name: DATA
              value: "/app/data/queryService.json"
---
apiVersion: v1
kind: Service
metadata:
  name: query-srv
spec:
  selector:
    app: query
  type: ClusterIP
  ports:
    - name: query
      protocol: TCP
      port: 4001
      targetPort: 4001


